server:
  port: 80
  
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/petshop?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: a
    driver-class-name: com.mysql.jdbc.Driver
    hikari.readOnly: false
    hikari.connectionTimeout: 60000
    hikari.idleTimeout: 60000
    hikari.validationTimeout: 3000
    hikari.maxLifetime: 60000
    hikari.loginTimeout: 5
    hikari.maximumPoolSize: 60
    hikari.minimumIdle: 10
  mail: 
    #邮箱服务器地址
    host: smtp.qq.com
    #用户名
    username: 1350979635@qq.com
    #密码
    password: tkkxphwjauxpifdg
    default-encoding: UTF-8
    #在阿里云上使用非ssl方式（25端口）发送邮件是行不通的，会被禁止，所以用ssl方式，ssl方式有两个端口465和994
    #，这里使用465端口。但在本地可以用非ssl方式（25端口）
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          # 如果设置false，可以不设置用户名和密码，当然也得看你的对接的平台是否支持无密码进行访问的
          auth: true
          starttls:
            enable: true
            required: true
      imap:
        ssl: 
          socketFactory:
            fallback: false
#以谁来发送邮件  用户自定义参数
mail:
  fromMail:
    addr: 1350979635@qq.com   

logging:
  level:
    com:
     song: debug
     

