server:
  port: 80
  
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/article?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: a
    driver-class-name: com.mysql.jdbc.Driver
    
logging:
  level:
    com:
     sw: debug
     

